# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches:
  #     - "*"
  pull_request:
    branches:
    - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Runs a single command using the runners shell
      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
        if: success()
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
      - name: Running script to deploy the pod and create user in db
        run: |
          echo $HEAD_SHA
          FILE=`git diff-tree --no-commit-id --name-only -r $HEAD_SHA`
          echo $FILE
        shell: bash
        env:
          HEAD_SHA: ${{ steps.comment-branch.outputs.head_sha }}
          # FILES_ADDED: ${{ steps.files.outputs.added }}
          # FILES_MODIFIED: ${{ steps.files.outputs.modified }}
          # FILES_ALL: ${{ steps.files.outputs.all }}


