name: NPM GitHub Actions

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - name: Adding new stage
      run: echo "$GITHUB_EVENT_NAME"