name: NPM GitHub Actions

on:
  issue_comment:
    types: [created]

jobs:
  build:
    if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '/plan')
    runs-on: ubuntu-latest
    steps:
    - uses: xt0rted/pull-request-comment-branch@v1
      id: comment-branch
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v2
      if: success()
      with:
        ref: ${{ steps.comment-branch.outputs.head_ref }}

    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - name: Running a script
      run: ./script.sh
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}